version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts

  contact-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
